### PR TITLE
Fix build in Visual Studio 2017/2019 and GCC >= 7.2.0

### PR DESCRIPTION
**Pull request by m-byte918**
Too many arguments in lambda:
```
error C2664:  'void us_new_socket_context_on_open(const int,us_new_socket_context_t *,us_new_socket_t *(__cdecl *)(us_new_socket_t *,int))': cannot convert argument 3 from 'uWS::HttpContext<false>::init::<lambda_1a1e4fd2aa024a7b371578dc5ee59d10>' to 'us_new_socket_t *(__cdecl *)(us_new_socket_t *,int)'
```
Missing `this` keyword:
```
error: there are no arguments to 'us_new_socket_remote_address' that depend on a template parameter, so a declaration of 'us_new_socket_remote_address' must be available [-fpermissive]
             us_new_socket_remote_address(SSL, (us_new_socket_t*)this, buf, &ipLength);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by alexhultman** [comment]
Builds should be fine now

**Comment by sakidev** [comment]
Builds are still crashing on g++ 8.3.0.

You can use -fpermissive and it will compile tho

**Comment by alexhultman** [comment]
Builds perfectly fine with gcc 7.4.0. Do not enable -fpermissive and think you have solved anything. I bet you haven't updated uSockets properly

**Comment by sakidev** [comment]
I will try out 7.4 tomorrow, 8.3 doesn't build unless you enable -fpermissive.

Not sture about uSockets, I literally cloned the repos and tried today!

**Pull request closed without merging**
