### PR TITLE
UV_READABLE and UV_WRITABLE -> UWS_READABLE, UWS_WRITABLE

### PR DESCRIPTION
**Pull request by Sunstradamus**
Fixes name collision when compiling with libuv headers

### CODE REVIEW

**Comment by desertkun** [comment]
Thank you for this!

**Comment by alexhultman** [comment]
So the issue is when you combine libuv with for instance Epoll?

**Comment by alexhultman** [comment]
Are you having libuv loops and asio/epoll loops in the same program?

**Comment by desertkun** [comment]
No, it was simply `libuv`. On linux in my case. So I guess Epoll is being included wrong.

Also, you have several issues with CMakeLists as `add_library` has old/missing files included.

**Comment by alexhultman** [comment]
You are compiling with CMake? Who gave you CMake files?

**Comment by desertkun** [comment]
Yeah, I am using CMake with `CMakeLists.txt` from your repository.

Here's my fixed lines:
```
add_library(uWS src/Extensions.cpp src/Group.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp src/Epoll.cpp)
```

**Comment by alexhultman** [comment]
This repo has no CMake files and hasn't had for probably 1 year now. This sounds more like some kind of major mix up rather than an actual source problem.

**Comment by desertkun** [comment]
Yeah, sorry for misunderstanding. Seems like that was solely my problem.

**Comment by alexhultman** [comment]
I have reset the merge.

**Comment by Sunstradamus** [comment]
> So the issue is when you combine libuv with for instance Epoll?

Yes whenever you use libuv with Epoll or ASIO. Specifically [this line](https://github.com/libuv/libuv/blob/695afe8322e4e9d8fbd8fe3f30069bca31b74f11/include/uv.h#L723) causes a duplicate identifier when compiling.

```c
#include <uv.h>
#include <uWS/uWS.h>

int main() {
    uWS::Hub h;
    return 0;
}
```

**Comment by Sunstradamus** [comment]
I was originally using `USE_LIBUV` but after some random segfaults and freezing I poked around and realized that it wasn't thread safe unless compiled with Epoll + `UWS_THREADSAFE`

**Pull request merged**
