### PR TITLE
Issues 1659

### PR DESCRIPTION
**Pull request by atkaper**
Possible suggestion to solve https://github.com/uNetworking/uWebSockets/issues/1659
Might need to be made more in line with the coding standards, but should work as-is also.

### CODE REVIEW

**Comment by uNetworkingAB** [comment]
I'm generally not a fan of dynamic configs but this only happens on slow path so could be reasonable.

Can you add a prefix like UWS_

**Comment by atkaper** [comment]
@uNetworkingAB renamed it as you suggested.

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/commit/75a525655fc865db4d3175cdcefa5a74a825e4df

**Comment by atkaper** [comment]
UWS_HTTP_MAX_HEADERS_SIZE already in master version, so closing pr.

**Pull request closed without merging**
