### PR TITLE
loop through the list returned by getaddrinfo

### PR DESCRIPTION
**Pull request by witaly-iwanow**
getaddrinfo returns a linked list, you should loop through it and try entries until you succeed:
http://beej.us/guide/bgnet/html/multi/syscalls.html#getaddrinfo

Here's an example of doing it properly. Curl tries to connect to localhost, getaddrinfo returns the list with ::1 as the first entry, connection to it fails and curl proceeds to the next entry which is good old IPv4 127.0.0.1 and it succeeds:
```
curl -v localhost:8000
* Rebuilt URL to: localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
...
```

### CODE REVIEW

**Comment by alexhultman** [comment]
Client connection is lacking currently, you also need to do those calls in a separate thread to keep it "async" as it currently can block if DNS resolution takes time.

**Comment by witaly-iwanow** [comment]
Not sure it's the right place to discuss that SSL init change, but anyway, I experienced the same behaviour - it did cause a crash on macOS and Windows in my set up (my own code + uWS source + uv source + static ssl and crypto, all linked together into an executable without any external dependencies)

**Comment by alexhultman** [comment]
It is reset now

**Comment by alexhultman** [comment]
All per-platform code will be moved to uSockets repo, you can tinker with that repo if you want

**Pull request closed without merging**
