### PR TITLE
Instructions for installing libuv on Debian|Ubuntu

### PR DESCRIPTION
**Pull request by alexslipknot**

### CODE REVIEW

**Comment by alexhultman** [comment]
Why is there no zlib or ssl packages? And why libuv1 when libuv1-dev has this as dependency. So many questions

**Comment by alexslipknot** [comment]
@alexhultman indeed. Please excuse me. I just want to inform you that `libuv` does not have candidate to install. So on Debian/Ubuntu you have to install `libuv1`

**Comment by alexhultman** [comment]
Shouldn't it be -dev packages?

**Comment by alexslipknot** [comment]
To be sure I did `make` on clean fresh installed Ubuntu. So I found that `zlib` (`zlib1g-dev`) library is already installed. So I removed it. Also I found that on fresh Ubuntu `libssl-dev` is absent . So I've added it. Thanks for the tip.

**Comment by alexhultman** [comment]
I'm not feeling this PR, thanks

**Pull request closed without merging**
