### PR TITLE
Allow to set send/recv buff size

### PR DESCRIPTION
**Pull request by noobxinyu**

### CODE REVIEW

**Comment by alexhultman** [comment]
Aren't there settable via config files?

**Comment by noobxinyu** [comment]
It would be a bit intrusive to the system and not flexible per application. Also a feed handler / trading gateway should have totally different settings.

**Comment by alexhultman** [comment]
Maybe better to use the getFd() function and do whatever

**Comment by noobxinyu** [comment]
I thought this might be parallel with cord/nodelay settings. But anyway it is your call.

**Pull request closed without merging**
