### PR TITLE
Allow different handlers for GET and WS for same route (#860)

### PR DESCRIPTION
**Pull request by not-implemented**
I made a pull-request out of the proposal from @szmarczak (slightly simplified).

Seems to work. Currently I do not see any drawbacks.

Btw.: I didn't fully understand the `req->setYield()` concept of the router, as it would make sense here, when multiple handlers for the same route could be registered.

### CODE REVIEW

**Comment by alexhultman** [comment]
Maybe I'm a total buzzkill now but the problem is that you add more work to be done for everyone, even if you don't have the same route for Http and WebSockets.

A proper solution would change the router so that two routes can be on the same path and that it only checks for sec-websocket-key if that very route has two registered handlers - because it is only in that case it can be both.

**Comment by not-implemented** [comment]
Hmm ... do you mean CPU-work or programmers-work?

CPU-work: Okay, the header lookup in HttpContext.h is done everytime then, even if no "ws" route is registered, I see. The second lookup in App.h is a little overhead, yes.
programmers-work: Should be the same - the interface does not change, or am I wrong?

But yes, maybe it is more flexible to have a list of handlers in `HttpRouter::Node` ... maybe I'll try around with `std::vector<short> handlers;` there.

Btw. (little off-topic): This would also not solve the problem to set additional custom headers for a WebSocket-Upgrade-Response - first I thought, this handler-list will be a handy interface for that - but registering a GET-handler, calling `res->setHeader()` and `req->setYield(true)` to forward it to the WS-Handler will not work - but this will be a different feature, I'll think about it :-)

**Comment by szmarczak** [comment]
@not-implemented The CPU one.

I think it's needed to create a `HttpRouter::find` function and make `executeHandlers` use that `find` function. Then, when attaching a GET handler we check if there's one already. If so, move it and attach a new one:

```cpp
if (req->getHeader("sec-websocket-key").length() == 24) {
    movedHandler(res, req);
} else {
    newHandler(res, req);
}
```

The same with the WS handler, just with the inversed `if` statement.

**Comment by alexhultman** [comment]
Yes that's a good solution I think - you only pay the extra cost if you really need it and only for that route

**Comment by alexhultman** [comment]
Have a try with latest alpha

**Pull request closed without merging**
