### PR TITLE
HTTP Client Support, Multi-OS Cmake, fixed compiler Warnings

### PR DESCRIPTION
**Pull request by mbmathews**
Project was to implement basic HTTP Client support in addition to basic Web socket client.  This is useful for implementing micro-services, keeping service to service communication fast and lean.   

Appreciate comments, our team will be using this going forward and will plan on making updates as issues and new capabilities arise.

### CODE REVIEW

**Comment by alexhultman** [comment]
Hmm... This is a very opinionated PR. Probably best off as a fork.

**Comment by mbmathews** [comment]
Works for me just wanted you to be aware.

Best.

Mike Mathews
mike@themathews.net<mailto:mike@themathews.net>
(m) 425-765-1237

On Jun 25, 2017, at 1:22 PM, Alex Hultman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm... This is a very opinionated PR. Probably best off as a fork.

-

**Comment by Convery** [comment]
So, any progress on merging this? Would be really nice to have rather than adding libcurl for basic requests.

**Comment by mbmathews** [comment]
I got turned down by Alex and then ran into some multithreading issues with it so I abandoned it in favor of libWebSockets.  Too bad really.  I thought it was a good idea too.

If it is single threaded it works pretty well.

Mike Mathews
mike@themathews.net<mailto:mike@themathews.net>
(m) 425-765-1237

On Aug 10, 2017, at 7:53 PM, Convery <notifications@github.com<mailto:notifications@github.com>> wrote:


So, any progress on merging this? Would be really nice to have rather than adding libcurl for basic requests.

-

**Pull request closed without merging**
