### PR TITLE
re-add custom ssl_ciphers support

### PR DESCRIPTION
**Pull request by shaharmor**
Follow up of https://github.com/uNetworking/uSockets/pull/179
Fixes https://github.com/uNetworking/uWebSockets/issues/1437

### CODE REVIEW

**Comment by alexhultman** [comment]
You need to bump uSockets submodule

**Comment by shaharmor** [comment]
> You need to bump uSockets submodule

Done. Updated to the latest commit on master

**Comment by alexhultman** [comment]
This one needs review since it brings lots of uSockets changes along

**Comment by shaharmor** [comment]
> This one needs review since it brings lots of uSockets changes along

Is there anything I can do to help? Who can review it?

**Comment by alexhultman** [comment]
I'm not sure if master uSockets compiles on Windows

**Comment by shaharmor** [comment]
If you want, you can create a new branch in uSockets from the latest used commit, and then we can add my commit to that branch... It will allow for only adding my change, but eventually the latest changes will have to be reviewed

**Comment by alexhultman** [comment]
I don't provide multiple branches of development

**Pull request closed without merging**
