### PR TITLE
Add run_one method to Libuv and Asio

### PR DESCRIPTION
**Pull request by Tai7sy**
Add run_one method to Libuv, Asio.
Epoll not

### CODE REVIEW

**Comment by alexhultman** [comment]
run_one is not the naming convention used. runOne would be, but I'm wondering why you would need this? A proper solution would only need run, nothing else. Integrations should be made at the polling (eventing) layer.

**Comment by Tai7sy** [comment]
I start many servers and stop some when receive some message. But there is no stop method(and it maybe hard to force terminate a server in another thread safely). 
In the beginning, I use while/poll/Sleep so i can break the whileloop when needed, then I found a run_one would be better, because it use the eventloop in libuv(or some other) rather than a stupid Sleep.
What's more, I think these i/o libraries support runOne, so there must be some situation we can use it.

**Comment by alexhultman** [comment]
You need to go back to the drawing board and redesign your server how it's supposed to work instead of adding hacks to work around your own design limitations.

**Comment by abrownsword** [comment]
I think the correct paradigm on libuv is to call loop->stop().  Or I guess that’s uv_loop_stop() if I’m not using a c++ wrapper.  There are also alternate run modes for loops, but I don’t like those much.  And runOne seems like a poor paradigm, particularly if your objective is to start and stop a server on demand.  If you want to act per iteration use a per iteration event, if you want to stop the loop... use stop.

**Comment by alexhultman** [comment]
This lib is async -> it runs on events only. Just like Node.js the loop will automatically "fall through" once there is no queued up async events. This is how you close it down if you really want that. You can look in the tests source, there are about 50 examples of how to properly do this. If you need more info you can take a quick look at Node.js design principles and apply them here.

**Comment by alexhultman** [comment]
Also note that your design will leak memory and file descriptors if you just hack in a runOnce method and exit that way. You need to let the loop run and fall through. Hub::run(); will return "fall through" once it is ready to do so.

**Comment by abrownsword** [comment]
Tai7sy:  the libuv paradigm for stopping a run loop in another thread is probably to use uv_async_t, and have the handler of that event (which is on the thread of the run loop) call uv_loop_stop once it has properly processed any cleanup that needs to be done.  Trying to take control of the loop’s iteration process by calling it one iteration at a time is going to be fraught with problems, as Alex points out.

**Comment by Tai7sy** [comment]
Thanks for these advice.
Now I have understood how the uWS works and the problem in my design of my program.
Just call close() and waiting for the run() to 'fall through' automatically seems to be more elegant and the right way.
Examples in the tests helped me a lot to understand and redesign the procedure of my program. Thanks again.

**Pull request closed without merging**
