### PR TITLE
Backend.h #ifdef patches

### PR DESCRIPTION
**Pull request by rindeal**

### CODE REVIEW

**Comment by alexhultman** [comment]
Follow existing style

**Comment by rindeal** [comment]
https://www.youtube.com/watch?v=DK_0jXPuIr0

**Comment by alexhultman** [comment]
I mean exactly what I wrote. Closing until fixed

**Comment by rindeal** [comment]
There are many things that can be styled ranging from commit messages to whitespaces. I have some telepathy issues right now so I'd appreciate if you could write down exactly what's your problem.

**Comment by alexhultman** [comment]
If you remove second commit you'll be fine.

**Comment by rindeal** [comment]
I've forced push the change, but GH hasn't updated the PR, go figure.

**Pull request closed without merging**
