### PR TITLE
Allow passing any functor to cork; no need for type erasure here

### PR DESCRIPTION
**Pull request by JWalker1995**

### CODE REVIEW

**Comment by alexhultman-2fa** [comment]
What is the gain in having different callbacks for certain cases? Compiling with LTO produces the same result.

**Comment by JWalker1995** [comment]
I didn't realize the compiler was that smart. Feel free to close.

**Comment by alexhultman-2fa** [comment]
I pasted an example in compilerexplorer and it did actually not compile down to nothing - but with "function2" (another implementation) it did. So technically I'm wrong, but a solution would be to revert back to using function2 rather than put in specialized cases.

**Comment by alexhultman-2fa** [comment]
I tested a more practical case, such as with cork - it does constant fold to zero cost in that case :)

**Pull request closed without merging**
