### PR TITLE
HAVE_REUSEPORT: Other TCP/IP stacks may have SO_REUSEPORT too

### PR DESCRIPTION
**Pull request by saper**
Do not use __linux for this feature.

### CODE REVIEW

**Comment by saper** [comment]
All tests passed fine on Linux with this code.

**Comment by alexhultman** [comment]
You are moving the same OS check from source code to makefile

**Comment by saper** [comment]
Yes, because with #705 I am adding FreeBSD and it makes little sense to add `|| defined (__FreeBSD__) || defined (somethingelese)` every time in the source code. Actually I think OS X has it available too (cannot test here).

**Comment by alexhultman** [comment]
So make it a macro - the build script should not tell the source what to do, it should simply build the sources. From what I have gathered SO_REUSEPORT on freebsd os x is not the same as on Linux

**Pull request closed without merging**
