### PR TITLE
Add a client example.

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by alexhultman** [comment]
Where is argv?

**Comment by alkino** [comment]
My bad. I firstly test with a hardcoded url. So I modify it, and don't try it again!

**Comment by alkino** [comment]
My bad. I firstly test with a hardcoded url. So I modify it, and don't try it again!

**Comment by alkino** [comment]
My bad. I firstly test with a hardcoded url. So I modify it, and don't try it again!

**Comment by alkino** [comment]
My bad. I firstly test with a hardcoded url. So I modify it, and don't try it again!

**Comment by alkino** [comment]
My bad. I firstly test with a hardcoded url. So I modify it, and don't try it again!

**Pull request closed without merging**
